defaultSemverRangePrefix: ""

packageExtensions:
  "adm-zip@0.x":
    dependencies:
      original-fs: ^1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.js
