name: 'Download a Build Artifact Outside'
description: 'Download a build artifact that was previously uploaded in the workflow by the upload-artifact action outside the current project'
author: 'sashkashishka'
inputs: 
  name:
    description: 'Artifact name'
    required: false
  path:
    description: 'Destination path'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
